server:
  port: 8082
  servlet:
    context-path: /personal-test

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

pt:
  backend:
    url: http://localhost:8081/pt-backend/api


